# Generated by Django 4.2.23 on 2024-01-01 00:00:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_account_status_user_archived_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_file', models.ImageField(upload_to='bird_images/%Y/%m/%d/')),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload_status', models.CharField(choices=[('UPLOADING', 'Uploading'), ('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='UPLOADING', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_duration', models.DurationField(blank=True, null=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_uploads', to='users.user')),
            ],
            options={
                'verbose_name': 'Image Upload',
                'verbose_name_plural': 'Image Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageProcessingResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detected_species', models.CharField(blank=True, choices=[('CHINESE_EGRET', 'Chinese Egret'), ('WHISKERED_TERN', 'Whiskered Tern'), ('GREAT_KNOT', 'Great Knot')], max_length=50, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('bounding_box', models.JSONField(blank=True, default=dict)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('OVERRIDDEN', 'Overridden')], default='PENDING', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('is_overridden', models.BooleanField(default=False)),
                ('overridden_species', models.CharField(blank=True, choices=[('CHINESE_EGRET', 'Chinese Egret'), ('WHISKERED_TERN', 'Whiskered Tern'), ('GREAT_KNOT', 'Great Knot')], max_length=50, null=True)),
                ('override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_result', to='image_processing.imageupload')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_overridden', to='users.user')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_reviewed', to='users.user')),
            ],
            options={
                'verbose_name': 'Image Processing Result',
                'verbose_name_plural': 'Image Processing Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_images', models.IntegerField(default=0)),
                ('processed_images', models.IntegerField(default=0)),
                ('failed_images', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_batches', to='users.user')),
                ('images', models.ManyToManyField(related_name='processing_batches', to='image_processing.imageupload')),
            ],
            options={
                'verbose_name': 'Processing Batch',
                'verbose_name_plural': 'Processing Batches',
                'ordering': ['-created_at'],
            },
        ),
    ]
