# Generated by Django 4.2.23 on 2025-08-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0003_add_missing_storage_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprocessingresult',
            name='total_detections',
            field=models.IntegerField(default=0),
        ),
    ]
