# Generated by Django 4.2.23 on 2025-09-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0007_modelevaluationrun_modelperformancemetrics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata including ground truth annotations'),
        ),
        migrations.AlterField(
            model_name='imageprocessingresult',
            name='ai_model',
            field=models.CharField(choices=[('YOLO_V5', 'YOLOv5'), ('YOLO_V8', 'YOLOv8'), ('YOLO_V9', 'YOLOv9'), ('CHINESE_EGRET_V1', '🏆 Chinese Egret Specialist (99.46% mAP)')], default='YOLO_V8', max_length=20),
        ),
        migrations.AlterField(
            model_name='imageprocessingresult',
            name='model_confidence_threshold',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
        ),
    ]
