# Generated by Django 4.2.23 on 2025-09-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0008_add_metadata_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='ai_processed_image',
            field=models.ImageField(blank=True, help_text='AI-optimized version for processing', null=True, upload_to='ai_processed/'),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='optimization_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of image optimization', max_length=20),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='optimized_image',
            field=models.ImageField(blank=True, help_text='Web-optimized version for fast delivery', null=True, upload_to='optimized/'),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail version for previews', null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='thumbnail_size',
            field=models.BigIntegerField(blank=True, help_text='Thumbnail file size in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='imageprocessingresult',
            name='detected_species',
            field=models.CharField(blank=True, choices=[('CHINESE_EGRET', 'Chinese Egret'), ('WHISKERED_TERN', 'Whiskered Tern'), ('GREAT_KNOT', 'Great Knot'), ('LITTLE_EGRET', 'Little Egret'), ('GREAT_EGRET', 'Great Egret'), ('INTERMEDIATE_EGRET', 'Intermediate Egret')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='imageprocessingresult',
            name='model_confidence_threshold',
            field=models.DecimalField(decimal_places=2, default=0.75, max_digits=3),
        ),
        migrations.AlterField(
            model_name='imageprocessingresult',
            name='overridden_species',
            field=models.CharField(blank=True, choices=[('CHINESE_EGRET', 'Chinese Egret'), ('WHISKERED_TERN', 'Whiskered Tern'), ('GREAT_KNOT', 'Great Knot'), ('LITTLE_EGRET', 'Little Egret'), ('GREAT_EGRET', 'Great Egret'), ('INTERMEDIATE_EGRET', 'Intermediate Egret')], max_length=50, null=True),
        ),
    ]
