# Generated by Django 4.2.23 on 2025-09-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0009_add_optimized_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='optimized_size',
            field=models.BigIntegerField(blank=True, help_text='Optimized image file size in bytes', null=True),
        ),
    ]
