# Generated by Django 5.0.1 on 2025-10-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0011_remove_imageevaluationresult_evaluation_run_and_more'),
    ]

    operations = [
        # All allocation fields already exist in database
        # No operations needed - database already has correct structure
    ]
