# Generated by Django 5.0.1 on 2025-10-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0012_auto_20251007_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='file_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of file content', max_length=64),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='is_compressed',
            field=models.BooleanField(default=False, help_text='Whether image has been optimized'),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='archive_path',
            field=models.CharField(blank=True, help_text='Path to archived file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='optimized_image',
            field=models.ImageField(blank=True, help_text='Web-optimized version for fast delivery', null=True, upload_to='optimized/'),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail image', null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='thumbnail_size',
            field=models.BigIntegerField(blank=True, help_text='Thumbnail file size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='storage_tier',
            field=models.CharField(choices=[('HOT', 'Hot Storage'), ('WARM', 'Warm Storage'), ('COLD', 'Cold Storage'), ('ARCHIVE', 'Archive')], default='HOT', help_text='Storage tier for lifecycle management', max_length=20),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True, help_text='Last time file was accessed'),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='retention_days',
            field=models.IntegerField(default=365, help_text='Days to retain file'),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='processing_duration',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='processing_step',
            field=models.CharField(blank=True, choices=[('READING_FILE', 'Reading image file'), ('OPTIMIZING', 'Optimizing image'), ('DETECTING', 'Detecting birds'), ('SAVING', 'Saving results'), ('COMPLETE', 'Processing complete')], max_length=20),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='processing_progress',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
