# Generated by Django 5.0.1 on 2025-10-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0013_auto_20251007_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='archive_path',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='description',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='file_hash',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='image_width',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='is_compressed',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='last_accessed',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='optimized_image',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='processing_duration',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='processing_error',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='processing_progress',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='processing_status',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='processing_step',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='retention_days',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='storage_tier',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='thumbnail_size',
        ),
        migrations.RemoveField(
            model_name='processingresult',
            name='allocated_at',
        ),
    ]
