# Generated by Django 5.0.1 on 2025-10-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0014_initial_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingresult',
            name='detected_species',
            field=models.CharField(choices=[('Chinese_Egret', 'Chinese Egret'), ('Great_Egret', 'Great Egret'), ('Intermediate_Egret', 'Intermediate Egret'), ('Little_Egret', 'Little Egret'), ('Western_Cattle_Egret', 'Western Cattle Egret'), ('Pacific_Reef_Heron', 'Pacific Reef Heron')], help_text='AI-identified egret species', max_length=50),
        ),
        migrations.AlterField(
            model_name='processingresult',
            name='overridden_species',
            field=models.CharField(blank=True, choices=[('Chinese_Egret', 'Chinese Egret'), ('Great_Egret', 'Great Egret'), ('Intermediate_Egret', 'Intermediate Egret'), ('Little_Egret', 'Little Egret'), ('Western_Cattle_Egret', 'Western Cattle Egret'), ('Pacific_Reef_Heron', 'Pacific Reef Heron')], max_length=50, null=True),
        ),
    ]
