# Generated by Django 5.0.1 on 2025-10-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0016_add_all_detections_to_processing_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingresult',
            name='detected_species',
            field=models.CharField(choices=[('Chinese_Egret', 'Chinese Egret'), ('Great_Egret', 'Great Egret'), ('Intermediate_Egret', 'Intermediate Egret'), ('Little_Egret', 'Little Egret'), ('Western_Cattle_Egret', 'Western Cattle Egret'), ('Pacific_Reef_Heron', 'Pacific Reef Heron')], help_text='Primary AI-identified egret species (highest confidence)', max_length=200),
        ),
    ]
