# Generated by Django 5.0.1 on 2025-10-20 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0017_alter_processingresult_detected_species'),
        ('locations', '0009_add_allocation_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='allocated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='allocated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='allocated_to_census',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_results', to='locations.census'),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='allocated_to_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_results', to='locations.site'),
        ),
    ]
