# Generated by Django 5.0.1 on 2025-10-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('ADMIN', 'Admin'), ('FIELD_WORKER', 'Field Worker')], max_length=50, unique=True)),
                ('can_generate_reports', models.BooleanField(default=True)),
                ('can_modify_species', models.BooleanField(default=True)),
                ('can_add_sites', models.BooleanField(default=True)),
                ('can_add_birds', models.BooleanField(default=True)),
                ('can_process_images', models.BooleanField(default=True)),
                ('can_access_weather', models.BooleanField(default=True)),
                ('can_access_analytics', models.BooleanField(default=True)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
            },
        ),
    ]
