# Generated by Django 5.0.1 on 2025-10-17 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_system', '0004_update_field_worker_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_generate_reports', models.BooleanField(blank=True, default=None, null=True)),
                ('can_modify_species', models.BooleanField(blank=True, default=None, null=True)),
                ('can_add_sites', models.BooleanField(blank=True, default=None, null=True)),
                ('can_add_birds', models.BooleanField(blank=True, default=None, null=True)),
                ('can_process_images', models.BooleanField(blank=True, default=None, null=True)),
                ('can_access_weather', models.BooleanField(blank=True, default=None, null=True)),
                ('can_access_analytics', models.BooleanField(blank=True, default=None, null=True)),
                ('can_manage_users', models.BooleanField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_permission_overrides', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission_override', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Permission Override',
                'verbose_name_plural': 'User Permission Overrides',
            },
        ),
    ]
