# Generated by Django 5.0.1 on 2025-09-24 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_rename_weather_fiel_site_id_123456_idx_weather_fie_site_id_f58099_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherforecast',
            name='cloud_cover',
            field=models.IntegerField(blank=True, help_text='Cloud cover percentage', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='weatherforecast',
            name='precipitation_probability',
            field=models.IntegerField(blank=True, help_text='Precipitation probability percentage', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='weatherforecast',
            name='weather_code',
            field=models.IntegerField(blank=True, help_text='WMO weather code', null=True),
        ),
    ]
