# Generated by Django 5.0.1 on 2025-10-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weatherforecast_cloud_cover_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fieldworkschedule',
            name='weather_fie_site_id_f58099_idx',
        ),
        migrations.RemoveIndex(
            model_name='weatherforecast',
            name='weather_wea_site_id_4554ac_idx',
        ),
        migrations.AlterUniqueTogether(
            name='weatherforecast',
            unique_together=set(),
        ),
    ]
