# Generated by Django 5.0.1 on 2025-10-11 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_make_coordinates_required'),
        ('weather', '0004_initial_locations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldworkschedule',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_work_schedules', to='locations.site'),
        ),
        migrations.AddField(
            model_name='weatheralert',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='weather_alerts', to='locations.site'),
        ),
        migrations.AddField(
            model_name='weatherforecast',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_forecasts', to='locations.site'),
        ),
        migrations.AddIndex(
            model_name='fieldworkschedule',
            index=models.Index(fields=['site', 'planned_date'], name='weather_fie_site_id_f58099_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherforecast',
            index=models.Index(fields=['site', 'forecast_date'], name='weather_wea_site_id_4554ac_idx'),
        ),
    ]
