# Generated by Django 4.2.23 on 2025-08-14 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fauna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdCensus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField()),
                ('census_date', models.DateField()),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('IMAGE_PROCESSING', 'Image Processing')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Bird Censuses',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location_desc', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='site_images/')),
                ('is_archived', models.BooleanField(default=False)),
                ('species', models.ManyToManyField(related_name='sites', through='locations.BirdCensus', to='fauna.species')),
            ],
        ),
        migrations.AddField(
            model_name='birdcensus',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.site'),
        ),
        migrations.AddField(
            model_name='birdcensus',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fauna.species'),
        ),
        migrations.AddField(
            model_name='birdcensus',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='birdcensus',
            unique_together={('site', 'species', 'census_date', 'source')},
        ),
    ]
