# Generated by Django 4.2.23 on 2025-08-14 11:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observation_date', models.DateField()),
                ('weather_conditions', models.CharField(blank=True, help_text='Weather during observation', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='General observation notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Census Observation',
                'verbose_name_plural': 'Census Observations',
                'ordering': ['-observation_date'],
            },
        ),
        migrations.CreateModel(
            name='SpeciesObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('species_name', models.CharField(help_text='Common or scientific name', max_length=200)),
                ('count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('behavior_notes', models.TextField(blank=True, help_text='Behavior, age, sex, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('census', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_observations', to='locations.censusobservation')),
            ],
            options={
                'verbose_name': 'Species Observation',
                'verbose_name_plural': 'Species Observations',
                'ordering': ['species_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['name'], 'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
        migrations.RemoveField(
            model_name='site',
            name='image',
        ),
        migrations.RemoveField(
            model_name='site',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='site',
            name='location_desc',
        ),
        migrations.RemoveField(
            model_name='site',
            name='species',
        ),
        migrations.AddField(
            model_name='site',
            name='coordinates',
            field=models.CharField(blank=True, help_text='Latitude, Longitude', max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_type',
            field=models.CharField(choices=[('wetland', 'Wetland'), ('forest', 'Forest'), ('grassland', 'Grassland'), ('urban', 'Urban'), ('coastal', 'Coastal'), ('mountain', 'Mountain'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('monitoring', 'Under Monitoring'), ('restricted', 'Restricted Access')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='BirdCensus',
        ),
        migrations.AddField(
            model_name='censusobservation',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='census_observations', to='locations.site'),
        ),
        migrations.AlterUniqueTogether(
            name='censusobservation',
            unique_together={('site', 'observation_date')},
        ),
    ]
