# Generated by Django 5.0.1 on 2025-10-11 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='censusobservation',
            name='behavior_notes',
        ),
    ]
