# Generated by Django 5.0.1 on 2025-10-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_behavior_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='coordinates',
            field=models.CharField(help_text='Latitude, Longitude (e.g., 14.5995, 120.9842)', max_length=100),
        ),
    ]
