# Generated by Django 5.0.1 on 2025-10-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_make_coordinates_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusobservation',
            name='family',
            field=models.CharField(blank=True, help_text='Bird family/category (e.g., HERONS AND EGRETS)', max_length=100),
        ),
    ]
