# Generated by Django 4.2.23 on 2025-09-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_mobiledataimport'),
    ]

    operations = [
        # Add performance indexes for frequently queried fields
        migrations.AddIndex(
            model_name='censusobservation',
            index=models.Index(fields=['site', 'observation_date'], name='census_site_date_idx'),
        ),
        migrations.AddIndex(
            model_name='censusobservation',
            index=models.Index(fields=['-observation_date'], name='census_date_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='speciesobservation',
            index=models.Index(fields=['species_name'], name='species_name_idx'),
        ),
        migrations.AddIndex(
            model_name='speciesobservation',
            index=models.Index(fields=['census'], name='species_census_idx'),
        ),
        migrations.AddIndex(
            model_name='mobiledataimport',
            index=models.Index(fields=['submitted_by', 'status'], name='mobile_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='mobiledataimport',
            index=models.Index(fields=['-created_at'], name='mobile_created_desc_idx'),
        ),
    ]
