# Generated by Django 4.2.23 on 2025-09-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='censusobservation',
            name='census_site_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='censusobservation',
            name='census_date_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='mobiledataimport',
            name='mobile_user_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='mobiledataimport',
            name='mobile_created_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='speciesobservation',
            name='species_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='speciesobservation',
            name='species_census_idx',
        ),
        migrations.AddField(
            model_name='site',
            name='ai_processed_image',
            field=models.ImageField(blank=True, help_text='AI-optimized version for processing', null=True, upload_to='ai_processed/'),
        ),
        migrations.AddField(
            model_name='site',
            name='optimization_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of image optimization', max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='optimized_image',
            field=models.ImageField(blank=True, help_text='Web-optimized version for fast delivery', null=True, upload_to='optimized/'),
        ),
        migrations.AddField(
            model_name='site',
            name='optimized_size',
            field=models.BigIntegerField(blank=True, help_text='Optimized image file size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='original_size',
            field=models.BigIntegerField(blank=True, help_text='Original image file size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail version for previews', null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='site',
            name='thumbnail_size',
            field=models.BigIntegerField(blank=True, help_text='Thumbnail file size in bytes', null=True),
        ),
    ]
