# Generated by Django 5.0.1 on 2025-10-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_censusobservation_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censusobservation',
            name='family',
            field=models.CharField(blank=True, help_text='Bird family (optional)', max_length=100),
        ),
    ]
