# Generated by Django 5.0.1 on 2025-10-12 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_censusobservation_family'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='census',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archive census instead of deleting'),
        ),
        migrations.AddField(
            model_name='censusmonth',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusmonth',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archive month instead of deleting'),
        ),
        migrations.AddField(
            model_name='censusobservation',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusobservation',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archive observation instead of deleting'),
        ),
        migrations.AddField(
            model_name='censusyear',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusyear',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archive year instead of deleting'),
        ),
        migrations.AddField(
            model_name='site',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When the site was archived', null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_sites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='site',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archive site instead of deleting'),
        ),
    ]
