# Generated by Django 4.2.23 on 2025-09-24 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fauna', '0002_add_optimized_images'),
        ('locations', '0005_add_optimized_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesobservation',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_observations', to='fauna.species'),
        ),
        migrations.AlterField(
            model_name='speciesobservation',
            name='species_name',
            field=models.CharField(help_text='Common or scientific name (legacy field)', max_length=200),
        ),
    ]
