# Generated by Django 5.0.1 on 2025-10-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_census_archived_at_census_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='allocation_notes',
            field=models.TextField(blank=True, help_text='Notes specific to AI/image processing allocation'),
        ),
    ]
