# Generated by Django 5.0.1 on 2025-10-15 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_add_allocation_notes_to_census'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='census',
            name='allocation_notes',
        ),
    ]
