# Generated by Django 5.0.1 on 2025-10-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_populate_species_foreign_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='area_hectares',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Site area in hectares', max_digits=10, null=True),
        ),
    ]
