# Generated by Django 5.0.1 on 2025-10-15 05:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0015_add_allocation_history'),
        ('locations', '0008_remove_allocation_notes_from_census'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('bird_count', models.PositiveIntegerField(help_text='Number of birds allocated')),
                ('observation_date', models.DateField(help_text='Date of the census observation')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this allocation')),
                ('allocated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_history', to=settings.AUTH_USER_MODEL)),
                ('census', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_history', to='locations.census')),
                ('processing_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_history', to='image_processing.processingresult')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_history', to='locations.site')),
            ],
            options={
                'verbose_name': 'Allocation History',
                'verbose_name_plural': 'Allocation History',
                'ordering': ['-allocated_at'],
            },
        ),
    ]
