# Generated by Django 5.0.1 on 2025-10-07 16:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauna', '0002_add_optimized_images'),
        ('locations', '0008_site_area_hectares'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSpeciesCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_count', models.PositiveIntegerField(default=0, help_text='Total birds of this species observed at this site')),
                ('last_observation_date', models.DateField(blank=True, help_text='Most recent observation date', null=True)),
                ('observation_count', models.PositiveIntegerField(default=0, help_text='Number of observations of this species')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this species presence is verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('monthly_counts', models.JSONField(default=dict, help_text='Bird counts by month (YYYY-MM: count)')),
                ('yearly_counts', models.JSONField(default=dict, help_text='Bird counts by year (YYYY: count)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_from_census', models.DateTimeField(blank=True, help_text='Last time updated from census data', null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_counts', to='locations.site')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_counts', to='fauna.species')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_species_counts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Species Count',
                'verbose_name_plural': 'Site Species Counts',
                'ordering': ['site', 'species__name'],
                'indexes': [models.Index(fields=['site', 'species'], name='locations_s_site_id_4e59e0_idx'), models.Index(fields=['site', 'is_verified'], name='locations_s_site_id_b58748_idx'), models.Index(fields=['species', 'total_count'], name='locations_s_species_d2d32f_idx')],
                'unique_together': {('site', 'species')},
            },
        ),
    ]
