# Generated by Django 5.0.1 on 2025-10-07 17:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_sitespeciescount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('add_census', 'Add Census Observation'), ('edit_census', 'Edit Census Observation'), ('delete_census', 'Delete Census Observation'), ('add_species', 'Add Species to Census'), ('edit_species', 'Edit Species Count'), ('delete_species', 'Remove Species from Census'), ('edit_site', 'Edit Site Information')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('request_data', models.JSONField(help_text='JSON data containing the requested changes')),
                ('reason', models.TextField(help_text='Reason for the request from field worker')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text="Admin's review notes")),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the approved request was actually executed', null=True)),
                ('census', models.ForeignKey(blank=True, help_text='Census observation if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='locations.censusobservation')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(help_text='Site this request is related to', on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='locations.site')),
            ],
            options={
                'verbose_name': 'Data Change Request',
                'verbose_name_plural': 'Data Change Requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='locations_d_status_6626ec_idx'), models.Index(fields=['requested_by', 'status'], name='locations_d_request_47933d_idx'), models.Index(fields=['site', 'status'], name='locations_d_site_id_93cded_idx')],
            },
        ),
    ]
