# Generated by Django 5.0.1 on 2025-10-07 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_datachangerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='censusobservation',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When this record was archived', null=True),
        ),
        migrations.AddField(
            model_name='censusobservation',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_census', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='censusobservation',
            name='archived_reason',
            field=models.TextField(blank=True, help_text='Reason for archiving this record'),
        ),
        migrations.AddField(
            model_name='censusobservation',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Whether this census record is archived'),
        ),
    ]
