# Generated by Django 5.0.1 on 2025-10-07 20:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_censusobservation_archived_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('archive', 'Archived'), ('restore', 'Restored'), ('import', 'Imported'), ('verify', 'Verified'), ('batch_edit', 'Batch Edited')], max_length=20)),
                ('description', models.TextField(help_text='Description of the activity')),
                ('old_values', models.JSONField(blank=True, help_text='Previous field values (for updates)', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='New field values (for updates)', null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client information')),
                ('census', models.ForeignKey(help_text='Census observation this activity relates to', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='locations.censusobservation')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='census_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Census Activity Log',
                'verbose_name_plural': 'Census Activity Logs',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['census', 'performed_at'], name='locations_c_census__7cfd6a_idx'), models.Index(fields=['activity_type', 'performed_at'], name='locations_c_activit_30a31e_idx'), models.Index(fields=['performed_by', 'performed_at'], name='locations_c_perform_8cfbdc_idx')],
            },
        ),
    ]
