# Generated by Django 4.2.23 on 2025-08-14 14:26

from django.db import migrations

def populate_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    
    groups_to_create = ['Superadmin', 'Admin', 'Field Worker']
    
    for group_name in groups_to_create:
        Group.objects.get_or_create(name=group_name)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_groups),
    ]
