# Generated by Django 4.2.23 on 2025-09-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_account_status_user_archived_by_and_more'),
    ]

    operations = [
        # Add performance indexes for User model
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['employee_id'], name='user_employee_id_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='user_role_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['account_status'], name='user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_archived'], name='user_archived_idx'),
        ),
    ]
