# Generated by Django 4.2.23 on 2025-08-14 15:30

from django.db import migrations

def assign_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    admin_group, _ = Group.objects.get_or_create(name='Admin')
    field_worker_group, _ = Group.objects.get_or_create(name='Field Worker')

    # Define permissions for Admin
    admin_permissions = [
        # Species Management
        'add_species', 'change_species', 'delete_species', 'view_species',
        # Site Management
        'add_site', 'change_site', 'delete_site', 'view_site',
        # Bird Census Management
        'add_birdcensus', 'change_birdcensus', 'delete_birdcensus', 'view_birdcensus',
    ]

    # Define permissions for Field Worker
    field_worker_permissions = [
        # Species Management
        'view_species',
        # Site Management
        'view_site',
        # Bird Census Management
        'view_birdcensus',
    ]

    # Assign permissions to Admin group
    for codename in admin_permissions:
        try:
            perm = Permission.objects.get(codename=codename)
            admin_group.permissions.add(perm)
        except Permission.DoesNotExist:
            # This can happen if the model related to the permission has been removed
            print(f"Warning: Permission with codename '{codename}' not found.")

    # Assign permissions to Field Worker group
    for codename in field_worker_permissions:
        try:
            perm = Permission.objects.get(codename=codename)
            field_worker_group.permissions.add(perm)
        except Permission.DoesNotExist:
            print(f"Warning: Permission with codename '{codename}' not found.")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_populate_groups'),
        # Add dependencies on the initial migrations of other apps
        ('fauna', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(assign_permissions),
    ]
