# Generated by Django 5.0.1 on 2025-10-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_user_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_employee_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_role_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_archived_idx',
        ),
    ]
