# Generated by Django 5.0.1 on 2025-10-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_user_employee_id_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
