# Generated by Django 4.2.23 on 2025-08-14 15:45

from django.db import migrations

def populate_employee_ids(apps, schema_editor):
    User = apps.get_model('users', 'User')
    
    # Update the superadmin user
    superadmin = User.objects.filter(is_superuser=True).first()
    if superadmin:
        superadmin.employee_id = 'SUPER001'
        superadmin.username = 'SUPER001'  # Keep username for compatibility
        superadmin.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_employee_id_alter_user_username'),
    ]

    operations = [
        migrations.RunPython(populate_employee_ids),
    ]
