# Generated by Django 4.2.23 on 2025-08-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_populate_employee_ids'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
