# Generated by Django 5.0.1 on 2025-10-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_useractivity_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Format: YY-MMDD-NNN (e.g., 25-0118-001)', max_length=50, null=True, unique=True, verbose_name='Employee ID'),
        ),
    ]
