# Generated by Django 5.0.1 on 2025-10-16 09:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('FORGOTTEN', 'Forgotten Password'), ('ADMIN_RESET', 'Admin Reset'), ('SECURITY_RESET', 'Security Reset')], default='FORGOTTEN', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by_ip', models.CharField(blank=True, max_length=45)),
                ('reason', models.TextField(blank=True, help_text='Reason for password reset request')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('reset_token', models.CharField(blank=True, max_length=100, unique=True)),
                ('reset_token_expires', models.DateTimeField(blank=True, null=True)),
                ('reset_completed_at', models.DateTimeField(blank=True, null=True)),
                ('verification_questions', models.JSONField(blank=True, default=list)),
                ('verification_answers', models.JSONField(blank=True, default=list)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_password_resets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Request',
                'verbose_name_plural': 'Password Reset Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
