# Generated by Django 4.2.23 on 2025-08-14 15:58

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_default_superadmin(apps, schema_editor):
    User = apps.get_model('users', 'User')
    
    # Create the default superadmin as specified in the blueprint
    if not User.objects.filter(employee_id='010101').exists():
        User.objects.create(
            employee_id='010101',
            username='010101',  # Keep username for compatibility
            first_name='System',
            last_name='Administrator',
            role='SUPERADMIN',
            is_staff=True,
            is_superuser=True,
            is_active=True,
            password=make_password('avicast123')
        )
        print('Default superadmin created: 010101 / avicast123')

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_email'),
    ]

    operations = [
        migrations.RunPython(create_default_superadmin),
    ]
