# Generated by Django 5.0.1 on 2025-10-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical'), ('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='MEDIUM', max_length=20),
        ),
    ]
