# Generated by Django 5.0.1 on 2025-10-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_update_severity_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_ARCHIVED', 'User Archived'), ('USER_DISABLED', 'User Disabled'), ('SPECIES_ADDED', 'Species Added'), ('SPECIES_UPDATED', 'Species Updated'), ('SPECIES_ARCHIVED', 'Species Archived'), ('SITE_ADDED', 'Site Added'), ('SITE_UPDATED', 'Site Updated'), ('CENSUS_ADDED', 'Census Added'), ('CENSUS_UPDATED', 'Census Updated'), ('IMAGE_PROCESSED', 'Image Processed'), ('REPORT_GENERATED', 'Report Generated'), ('DATA_IMPORTED', 'Data Imported'), ('DATA_EXPORTED', 'Data Exported'), ('ADMIN_ACTION', 'Admin Action'), ('USER_ACTION', 'User Action'), ('CLIENT_ERROR', 'Client Error'), ('SYSTEM_ERROR', 'System Error'), ('API_ACCESS', 'API Access'), ('PAGE_VIEW', 'Page View')], max_length=50),
        ),
    ]
