# Generated by Django 4.2.23 on 2025-09-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='ai_processed_image',
            field=models.ImageField(blank=True, help_text='AI-optimized version for processing', null=True, upload_to='ai_processed/'),
        ),
        migrations.AddField(
            model_name='species',
            name='optimization_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of image optimization', max_length=20),
        ),
        migrations.AddField(
            model_name='species',
            name='optimized_image',
            field=models.ImageField(blank=True, help_text='Web-optimized version for fast delivery', null=True, upload_to='optimized/'),
        ),
        migrations.AddField(
            model_name='species',
            name='optimized_size',
            field=models.BigIntegerField(blank=True, help_text='Optimized image file size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='original_size',
            field=models.BigIntegerField(blank=True, help_text='Original image file size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail version for previews', null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='species',
            name='thumbnail_size',
            field=models.BigIntegerField(blank=True, help_text='Thumbnail file size in bytes', null=True),
        ),
    ]
