# Generated by Django 5.0.1 on 2025-10-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauna', '0002_add_optimized_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='description',
            field=models.TextField(blank=True, help_text='Additional description or notes about the species'),
        ),
        migrations.AddField(
            model_name='species',
            name='family',
            field=models.CharField(blank=True, help_text='Taxonomic family (e.g., Ardeidae for herons)', max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='image',
            field=models.ImageField(blank=True, help_text='Representative image of the species', null=True, upload_to='species_images/'),
        ),
        migrations.AlterField(
            model_name='species',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Whether this species is archived'),
        ),
        migrations.AlterField(
            model_name='species',
            name='iucn_status',
            field=models.CharField(choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered'), ('EW', 'Extinct in the Wild'), ('EX', 'Extinct')], help_text='IUCN conservation status', max_length=2),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(help_text='Common name of the species', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(help_text='Scientific name of the species', max_length=255, unique=True),
        ),
    ]
