# Generated by Django 5.0.1 on 2025-10-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauna', '0004_add_bird_family_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='family',
            field=models.CharField(blank=True, choices=[('HERONS AND EGRETS', 'Herons and Egrets'), ('IBISES & SPOONBILLS', 'Ibises & Spoonbills'), ('GEESE & DUCKS', 'Geese & Ducks'), ('GULLS, TERNS & SKIMMERRS', 'Gulls, Terns & Skimmers'), ('SHOREBIRDS-WADERS', 'Shorebirds-Waders'), ('RAILS, GALLINULES & COOTS', 'Rails, Gallinules & Coots'), ('PHEASANTS & FOWL', 'Pheasants & Fowl'), ('PIGEONS & DOVES', 'Pigeons & Doves'), ('CUCKOOS', 'Cuckoos'), ('SWIFTS & SWALLOWS', 'Swifts & Swallows'), ('RAILS & CRANES', 'Rails & Cranes'), ('EAGLES & HAWKS', 'Eagles & Hawks'), ('OWLS', 'Owls'), ('FALCONS', 'Falcons'), ('KINGFISHERS', 'Kingfishers'), ('BEE-EATERS', 'Bee-eaters'), ('HOOPOES', 'Hoopoes'), ('WOODPECKERS', 'Woodpeckers'), ('BARBETS', 'Barbets'), ('HORNBILLS', 'Hornbills'), ('PASSERINES', 'Passerines (Songbirds)'), ('CROWS & JAYS', 'Crows & Jays'), ('LARKS', 'Larks'), ('SWALLOWS & MARTINS', 'Swallows & Martins'), ('BULBULS', 'Bulbuls'), ('BABBLERS', 'Babblers'), ('WARBLERS', 'Warblers'), ('FLYCATCHERS', 'Flycatchers'), ('THRUSHES', 'Thrushes'), ('CHATS', 'Chats'), ('ROBINS', 'Robins'), ('SUNBIRDS', 'Sunbirds'), ('SPARROWS & FINCHES', 'Sparrows & Finches'), ('WEAVERS', 'Weavers'), ('WAXBILLS', 'Waxbills'), ('Ardeidae', 'Ardeidae (Herons, Egrets, Bitterns)'), ('Anatidae', 'Anatidae (Ducks, Geese, Swans)'), ('Charadriidae', 'Charadriidae (Plovers, Lapwings)'), ('Scolopacidae', 'Scolopacidae (Sandpipers, Snipes)'), ('Laridae', 'Laridae (Gulls, Terns, Skimmers)'), ('Rallidae', 'Rallidae (Rails, Gallinules, Coots)'), ('Accipitridae', 'Accipitridae (Eagles, Hawks, Kites)'), ('Falconidae', 'Falconidae (Falcons, Kestrels)'), ('Strigidae', 'Strigidae (Owls)'), ('Corvidae', 'Corvidae (Crows, Jays, Magpies)'), ('Alcedinidae', 'Alcedinidae (Kingfishers)'), ('Meropidae', 'Meropidae (Bee-eaters)'), ('Upupidae', 'Upupidae (Hoopoes)'), ('Picidae', 'Picidae (Woodpeckers)'), ('Bucerotidae', 'Bucerotidae (Hornbills)'), ('Pycnonotidae', 'Pycnonotidae (Bulbuls)'), ('Muscicapidae', 'Muscicapidae (Chats, Robins, Flycatchers)'), ('Turdidae', 'Turdidae (Thrushes)'), ('Sylviidae', 'Sylviidae (Warblers)'), ('Nectariniidae', 'Nectariniidae (Sunbirds)'), ('Passeridae', 'Passeridae (Sparrows)'), ('Fringillidae', 'Fringillidae (Finches)'), ('Ploceidae', 'Ploceidae (Weavers)'), ('Estrildidae', 'Estrildidae (Waxbills, Munias)'), ('ADDITIONAL SPECIES', 'Additional Species'), ('UNCATEGORIZED', 'Uncategorized'), ('OTHER', 'Other')], help_text='Bird family classification', max_length=100),
        ),
    ]
