# Generated by Django 5.0.1 on 2025-10-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauna', '0005_add_uncategorized_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='family',
            field=models.CharField(blank=True, choices=[('HERONS AND EGRETS', 'Herons and Egrets'), ('IBISES & SPOONBILLS', 'Ibises & Spoonbills'), ('GEESE & DUCKS', 'Geese & Ducks'), ('GULLS, TERNS & SKIMMERRS', 'Gulls, Terns & Skimmers'), ('SHOREBIRDS-WADERS', 'Shorebirds-Waders'), ('RAILS, GALLINULES & COOTS', 'Rails, Gallinules & Coots'), ('Ardeidae', 'Ardeidae (Herons, Egrets, Bitterns)'), ('ADDITIONAL SPECIES', 'Additional Species'), ('PHEASANTS & FOWL', 'Pheasants & Fowl'), ('PIGEONS & DOVES', 'Pigeons & Doves'), ('EAGLES & HAWKS', 'Eagles & Hawks'), ('OWLS', 'Owls'), ('FALCONS', 'Falcons'), ('KINGFISHERS', 'Kingfishers'), ('WOODPECKERS', 'Woodpeckers'), ('HORNBILLS', 'Hornbills'), ('CROWS & JAYS', 'Crows & Jays'), ('SWALLOWS & MARTINS', 'Swallows & Martins'), ('WARBLERS', 'Warblers'), ('FLYCATCHERS', 'Flycatchers'), ('THRUSHES', 'Thrushes'), ('SUNBIRDS', 'Sunbirds'), ('SPARROWS & FINCHES', 'Sparrows & Finches'), ('Anatidae', 'Anatidae (Ducks, Geese, Swans)'), ('Charadriidae', 'Charadriidae (Plovers, Lapwings)'), ('Scolopacidae', 'Scolopacidae (Sandpipers, Snipes)'), ('Laridae', 'Laridae (Gulls, Terns, Skimmers)'), ('Rallidae', 'Rallidae (Rails, Gallinules, Coots)'), ('Accipitridae', 'Accipitridae (Eagles, Hawks, Kites)'), ('Falconidae', 'Falconidae (Falcons, Kestrels)'), ('Strigidae', 'Strigidae (Owls)'), ('Corvidae', 'Corvidae (Crows, Jays, Magpies)'), ('Alcedinidae', 'Alcedinidae (Kingfishers)'), ('Picidae', 'Picidae (Woodpeckers)'), ('Bucerotidae', 'Bucerotidae (Hornbills)'), ('Muscicapidae', 'Muscicapidae (Chats, Robins, Flycatchers)'), ('Turdidae', 'Turdidae (Thrushes)'), ('Sylviidae', 'Sylviidae (Warblers)'), ('Nectariniidae', 'Nectariniidae (Sunbirds)'), ('Passeridae', 'Passeridae (Sparrows)'), ('Fringillidae', 'Fringillidae (Finches)'), ('UNCATEGORIZED', 'Uncategorized'), ('OTHER', 'Other')], help_text='Bird family classification', max_length=100),
        ),
    ]
