# Generated by Django 5.0.1 on 2025-10-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauna', '0006_cleanup_unused_families'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='family',
            field=models.CharField(blank=True, choices=[('HERONS AND EGRETS', 'Herons and Egrets'), ('GEESE & DUCKS', 'Geese & Ducks'), ('IBISES & SPOONBILLS', 'Ibises & Spoonbills'), ('SHOREBIRDS-WADERS', 'Shorebirds-Waders'), ('RAILS, GALLINULES & COOTS', 'Rails, Gallinules & Coots'), ('GULLS, TERNS & SKIMMERRS', 'Gulls, Terns & Skimmers'), ('ADDITIONAL SPECIES', 'Additional Species')], help_text='Bird family classification', max_length=100),
        ),
    ]
