# Generated by Django 5.0.1

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fauna', '0007_restrict_to_active_families'),
    ]

    operations = [
        # Create BirdFamily model
        migrations.CreateModel(
            name='BirdFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Family name (e.g., HERONS AND EGRETS)', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Display name (e.g., Herons and Egrets)', max_length=100)),
                ('category', models.CharField(choices=[('WATER_BIRDS', 'Water Birds'), ('LAND_BIRDS', 'Land Birds'), ('RAPTORS', 'Raptors'), ('SMALL_BIRDS', 'Small Birds'), ('SONGBIRDS', 'Songbirds'), ('SCIENTIFIC', 'Scientific Families'), ('OTHER', 'Other')], default='WATER_BIRDS', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of this family')),
                ('scientific_name', models.CharField(blank=True, help_text='Scientific family name (optional)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this family is available for selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bird Family',
                'verbose_name_plural': 'Bird Families',
                'ordering': ['category', 'display_name'],
                'abstract': False,
            },
        ),
    ]
