# Generated by Django 5.0.1

from django.db import migrations, models
import django.db.models.deletion


def migrate_family_data(apps, schema_editor):
    """Migrate existing family data from CharField to ForeignKey"""
    Species = apps.get_model('fauna', 'Species')
    BirdFamily = apps.get_model('fauna', 'BirdFamily')
    
    for species in Species.objects.all():
        if species.family:  # If the old field has a value
            # Try to find matching BirdFamily
            try:
                bird_family = BirdFamily.objects.get(name=species.family)
                species.family_new = bird_family
                species.save(update_fields=['family_new'])
            except BirdFamily.DoesNotExist:
                # If no match found, set to Additional Species
                additional_family = BirdFamily.objects.get(name='ADDITIONAL SPECIES')
                species.family_new = additional_family
                species.save(update_fields=['family_new'])


def reverse_migrate_family_data(apps, schema_editor):
    """Reverse migration - populate old field from new ForeignKey"""
    Species = apps.get_model('fauna', 'Species')
    
    for species in Species.objects.all():
        if species.family_new:
            species.family = species.family_new.name
            species.save(update_fields=['family'])
        else:
            species.family = ''
            species.save(update_fields=['family'])


class Migration(migrations.Migration):

    dependencies = [
        ('fauna', '0009_populate_birdfamily_data'),
    ]

    operations = [
        # First, add the new foreign key field as nullable
        migrations.AddField(
            model_name='species',
            name='family_new',
            field=models.ForeignKey(blank=True, help_text='Bird family classification', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fauna.birdfamily'),
        ),
        
        # Data migration to populate the new field based on existing data
        migrations.RunPython(
            migrate_family_data,
            reverse_migrate_family_data
        ),
        
        # Remove the old field
        migrations.RemoveField(
            model_name='species',
            name='family',
        ),
        
        # Rename the new field to the original name
        migrations.RenameField(
            model_name='species',
            old_name='family_new',
            new_name='family',
        ),
    ]
