# Generated by Django 5.0.1 on 2025-10-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='output_format',
            field=models.CharField(default='HTML', help_text='HTML, PDF, EXCEL', max_length=10),
        ),
    ]
