# Generated by Django 5.0.1 on 2025-10-07 15:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_new', '0002_generatedreport_output_format'),
        ('locations', '0001_initial'),
        ('fauna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_count', models.PositiveIntegerField(default=0, help_text='Total count across all sites')),
                ('sites_with_presence', models.PositiveIntegerField(default=0, help_text='Number of sites where this species is present')),
                ('last_observation_date', models.DateField(blank=True, null=True, help_text='Most recent observation date')),
                ('primary_habitats', models.JSONField(default=list, help_text='List of primary habitat types')),
                ('site_distribution', models.JSONField(default=dict, help_text='Count by site')),
                ('population_trend', models.CharField(default='STABLE', help_text='Population trend', max_length=20)),
                ('trend_confidence', models.DecimalField(decimal_places=2, default=0.5, help_text='Confidence in trend analysis', max_digits=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('species', models.OneToOneField(help_text='Link to main species record', on_delete=models.CASCADE, related_name='analytics', to='fauna.species')),
            ],
            options={
                'ordering': ['species__name'],
                'verbose_name': 'Species Analytics',
                'verbose_name_plural': 'Species Analytics',
            },
        ),
        migrations.CreateModel(
            name='SiteAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_birds_recorded', models.PositiveIntegerField(default=0, help_text='Total birds recorded at this site')),
                ('species_diversity', models.PositiveIntegerField(default=0, help_text='Number of different species recorded')),
                ('target_species_count', models.PositiveIntegerField(default=0, help_text='Number of target species present')),
                ('dominant_species', models.CharField(blank=True, help_text='Most abundant species', max_length=200)),
                ('species_composition', models.JSONField(default=dict, help_text='Species distribution by count')),
                ('total_census_observations', models.PositiveIntegerField(default=0, help_text='Total census observations')),
                ('last_survey_date', models.DateField(blank=True, null=True, help_text='Most recent survey date')),
                ('survey_frequency_days', models.PositiveIntegerField(default=30, help_text='Average days between surveys')),
                ('avg_temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Average temperature', max_digits=5, null=True)),
                ('avg_humidity', models.DecimalField(blank=True, decimal_places=2, help_text='Average humidity', max_digits=5, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.OneToOneField(help_text='Link to main site record', on_delete=models.CASCADE, related_name='analytics', to='locations.site')),
            ],
            options={
                'ordering': ['site__name'],
                'verbose_name': 'Site Analytics',
                'verbose_name_plural': 'Site Analytics',
            },
        ),
        migrations.CreateModel(
            name='CensusAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_birds', models.PositiveIntegerField(default=0, help_text='Total birds observed')),
                ('species_richness', models.PositiveIntegerField(default=0, help_text='Number of different species')),
                ('dominant_species', models.CharField(blank=True, help_text='Most abundant species', max_length=200)),
                ('species_breakdown', models.JSONField(default=dict, help_text='Count by species')),
                ('data_quality_score', models.DecimalField(decimal_places=2, default=1.0, help_text='Data quality score', max_digits=3)),
                ('verification_status', models.CharField(default='PENDING', help_text='Verification status', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('census_observation', models.OneToOneField(help_text='Link to main census observation', on_delete=models.CASCADE, related_name='analytics', to='locations.censusobservation')),
            ],
            options={
                'ordering': ['-census_observation__observation_date'],
                'verbose_name': 'Census Analytics',
                'verbose_name_plural': 'Census Analytics',
            },
        ),
        migrations.CreateModel(
            name='PopulationTrend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_length_days', models.PositiveIntegerField()),
                ('average_count', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peak_count', models.PositiveIntegerField()),
                ('minimum_count', models.PositiveIntegerField()),
                ('trend_direction', models.CharField(help_text='INCREASING, DECREASING, STABLE, FLUCTUATING', max_length=20)),
                ('trend_strength', models.CharField(help_text='STRONG, MODERATE, WEAK', max_length=20)),
                ('confidence_level', models.DecimalField(decimal_places=2, help_text='0.0 to 1.0', max_digits=5)),
                ('standard_deviation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coefficient_variation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sample_size', models.PositiveIntegerField()),
                ('correlated_factors', models.JSONField(default=list, help_text='Environmental factors that correlate with population')),
                ('seasonal_pattern', models.CharField(blank=True, max_length=100)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('methodology', models.TextField(blank=True, help_text='Analysis methodology description')),
                ('data_sources', models.JSONField(default=list, help_text='List of census observations used')),
                ('species_analytics', models.ForeignKey(on_delete=models.CASCADE, related_name='population_trends', to='analytics_new.speciesanalytics')),
            ],
            options={
                'ordering': ['-analysis_date'],
                'unique_together': {('species_analytics', 'period_start', 'period_end')},
                'verbose_name': 'Population Trend',
                'verbose_name_plural': 'Population Trends',
            },
        ),
    ]
