# Generated by Django 5.0.1 on 2025-10-16 02:43

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_new', '0004_initial_locations'),
        ('fauna', '0003_add_family_and_description_to_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_count', models.PositiveIntegerField(default=0, help_text='Total count across all sites')),
                ('sites_with_presence', models.PositiveIntegerField(default=0, help_text='Number of sites where this species is present')),
                ('last_observation_date', models.DateField(blank=True, null=True, help_text='Most recent observation date')),
                ('primary_habitats', models.JSONField(default=list, help_text='List of primary habitat types')),
                ('site_distribution', models.JSONField(default=dict, help_text='Count by site')),
                ('population_trend', models.CharField(default='STABLE', help_text='Population trend', max_length=20)),
                ('trend_confidence', models.DecimalField(decimal_places=2, default=0.5, help_text='Confidence in trend analysis', max_digits=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('species', models.OneToOneField(help_text='Link to main species record', on_delete=models.deletion.CASCADE, related_name='analytics', to='fauna.species')),
            ],
            options={
                'verbose_name': 'Species Analytics',
                'verbose_name_plural': 'Species Analytics',
                'ordering': ['species__name'],
            },
        ),
    ]
