# Generated by Django 5.0.1 on 2025-10-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_new', '0005_auto_20251016_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciesanalytics',
            options={'verbose_name': 'Census Analytics', 'verbose_name_plural': 'Census Analytics'},
        ),
        migrations.AddField(
            model_name='speciesanalytics',
            name='avg_humidity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='speciesanalytics',
            name='avg_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='speciesanalytics',
            name='data_quality_score',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Data quality score', max_digits=3),
        ),
        migrations.AddField(
            model_name='speciesanalytics',
            name='dominant_species',
            field=models.CharField(blank=True, help_text='Most abundant species', max_length=200),
        ),
        migrations.AddField(
            model_name='speciesanalytics',
            name='last_survey_date',
            field=models.DateField(blank=True, help_text='Most recent survey date', null=True),
        ),
        migrations.AddField(
            model_name='speciesanalytics',
            name='species_breakdown',
            field=models.JSONField(default=dict, help_text='Count by species'),
        ),
        migrations.AddField(
            model_name='speciesanalytics',
            name='species_composition',
            field=models.JSONField(default=dict, help_text='Species distribution by count'),
        ),
        migrations.AddField(
            model_name='speciesanalytics',
            name='species_diversity',
            field=models.PositiveIntegerField(default=0, help_text='Number of different species recorded'),
        ),
        migrations.AddField(
            model_name='speciesanalytics',
            name='species_richness',
            field=models.PositiveIntegerField(default=0, help_text='Number of different species'),
        ),
        migrations.AddField(
            model_name='speciesanalytics',
            name='survey_frequency_days',
            field=models.PositiveIntegerField(default=30, help_text='Average days between surveys'),
        ),
        migrations.AddField(
            model_name='speciesanalytics',
            name='target_species_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of target species present'),
        ),
        migrations.AddField(
            model_name='speciesanalytics',
            name='total_birds',
            field=models.PositiveIntegerField(default=0, help_text='Total birds observed'),
        ),
        migrations.AddField(
            model_name='speciesanalytics',
            name='total_birds_recorded',
            field=models.PositiveIntegerField(default=0, help_text='Total birds recorded at this site'),
        ),
        migrations.AddField(
            model_name='speciesanalytics',
            name='total_census_observations',
            field=models.PositiveIntegerField(default=0, help_text='Total census observations'),
        ),
        migrations.AddField(
            model_name='speciesanalytics',
            name='verification_status',
            field=models.CharField(default='PENDING', help_text='Verification status', max_length=20),
        ),
        migrations.AlterField(
            model_name='speciesanalytics',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
