# Generated by Django 4.2.23 on 2025-08-14 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the report template', max_length=200)),
                ('report_type', models.CharField(choices=[('census_summary', 'Census Summary Report'), ('species_diversity', 'Species Diversity Report'), ('population_trends', 'Population Trends Report'), ('site_comparison', 'Site Comparison Report'), ('seasonal_analysis', 'Seasonal Analysis Report')], max_length=30)),
                ('description', models.TextField(blank=True, help_text='Description of the report')),
                ('template_data', models.JSONField(help_text='Report template configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the generated report', max_length=200)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('html', 'HTML')], max_length=10)),
                ('file_path', models.CharField(blank=True, help_text='Path to the generated file', max_length=500)),
                ('parameters', models.JSONField(help_text='Parameters used to generate the report')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.reporttemplate')),
            ],
            options={
                'verbose_name': 'Generated Report',
                'verbose_name_plural': 'Generated Reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChartConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the chart configuration', max_length=200)),
                ('chart_type', models.CharField(choices=[('bar', 'Bar Chart'), ('line', 'Line Chart'), ('pie', 'Pie Chart'), ('scatter', 'Scatter Plot'), ('heatmap', 'Heatmap'), ('radar', 'Radar Chart')], max_length=20)),
                ('title', models.CharField(help_text='Chart title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of what the chart shows')),
                ('config_data', models.JSONField(help_text='Chart configuration in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this chart configuration is active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chart Configuration',
                'verbose_name_plural': 'Chart Configurations',
                'ordering': ['name'],
            },
        ),
    ]
